(()=>{
'use strict';
const $=id=>document.getElementById(id),NS='http://www.w3.org/2000/svg';
const canvas=$('canvas'),scene=$('scene'),input=$('jsonInput'),status=$('status'),detail=$('detailContent');
let current=null,zoom=1,tx=0,ty=0,drag=null,bounds={x:-500,y:-350,right:500,bottom:350};
const palette=['#4F5BDD','#0E8F7A','#D97706','#B64872','#2563EB','#7C3AED','#0891B2','#475569'];
function svg(tag,attrs={},text){const e=document.createElementNS(NS,tag);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v));if(text!==undefined)e.textContent=text;return e}
function wrap(text,max=12){const a=Array.from(String(text||'')),r=[];while(a.length)r.push(a.splice(0,max).join(''));return r.length?r:['']}
function resetScene(){scene.replaceChildren();bounds={x:Infinity,y:Infinity,right:-Infinity,bottom:-Infinity}}
function include(x,y,w,h){bounds.x=Math.min(bounds.x,x);bounds.y=Math.min(bounds.y,y);bounds.right=Math.max(bounds.right,x+w);bounds.bottom=Math.max(bounds.bottom,y+h)}
function edge(x1,y1,x2,y2,label='',color='#94A3B8',arrow=true){const p=svg('path',{d:`M ${x1} ${y1} C ${(x1+x2)/2} ${y1}, ${(x1+x2)/2} ${y2}, ${x2} ${y2}`,fill:'none',stroke:color,'stroke-width':2.5});scene.append(p);if(arrow){const ang=Math.atan2(y2-y1,x2-x1),s=9;const a1=[x2-s*Math.cos(ang-.5),y2-s*Math.sin(ang-.5)],a2=[x2-s*Math.cos(ang+.5),y2-s*Math.sin(ang+.5)];scene.append(svg('path',{d:`M ${a1[0]} ${a1[1]} L ${x2} ${y2} L ${a2[0]} ${a2[1]}`,fill:'none',stroke:color,'stroke-width':2.5}))}if(label){scene.append(svg('text',{x:(x1+x2)/2,y:(y1+y2)/2-8,'text-anchor':'middle',fill:'#64748B','font-size':12,'font-family':'system-ui,sans-serif'},label))}}
function node(x,y,title,{w=190,h=null,color=palette[0],desc='',filled=false,shape='rect'}={}){const lines=wrap(title,12),height=h||Math.max(54,lines.length*21+22),g=svg('g',{transform:`translate(${x},${y})`,style:'cursor:pointer'});let bg;if(shape==='diamond')bg=svg('polygon',{points:`0,${-height/2} ${w/2},0 0,${height/2} ${-w/2},0`,fill:filled?color:'#fff',stroke:color,'stroke-width':2});else bg=svg('rect',{x:-w/2,y:-height/2,width:w,height:height,rx:14,fill:filled?color:'#fff',stroke:color,'stroke-width':2});g.append(bg);lines.forEach((ln,i)=>g.append(svg('text',{x:0,y:(i-(lines.length-1)/2)*21+5,'text-anchor':'middle',fill:filled?'#fff':'#243046','font-size':14,'font-family':'system-ui,sans-serif','font-weight':filled?'700':'600'},ln)));g.onclick=()=>{detail.textContent=desc||title};scene.append(g);include(x-w/2-12,y-height/2-12,w+24,height+24);return {x,y,w,h:height}}
function title(text){scene.append(svg('text',{x:0,y:-300,'text-anchor':'middle',fill:'#1E293B','font-size':26,'font-family':'system-ui,sans-serif','font-weight':'800'},text));include(-260,-330,520,60)}
function renderConcept(d){title(d.title);const map=new Map(),center=d.nodes?.[0];if(!center)return;map.set(center.id,node(0,0,center.title,{color:palette[0],desc:center.description,filled:true,w:220}));const others=d.nodes.slice(1),r=260;others.forEach((n,i)=>{const a=(Math.PI*2*i/Math.max(1,others.length))-Math.PI/2;map.set(n.id,node(Math.cos(a)*r,Math.sin(a)*r,n.title,{color:palette[(i+1)%palette.length],desc:n.description}))});(d.relations||[]).forEach((rel,i)=>{const a=map.get(rel.from),b=map.get(rel.to);if(a&&b)edge(a.x,a.y,b.x,b.y,rel.label,palette[(i+1)%palette.length])})}
function renderFlowLike(d){title(d.title);const steps=d.steps||[],gap=225,start=-(steps.length-1)*gap/2;let prev=null;steps.forEach((s,i)=>{const n=node(start+i*gap,0,s.title,{color:palette[i%palette.length],desc:s.description,filled:i===0});if(prev)edge(prev.x+prev.w/2,prev.y,n.x-n.w/2,n.y,'',palette[i%palette.length]);prev=n})}
function renderDecision(d){title(d.title);let levelY=-160;function walk(n,x,depth,span){if(!n)return;const cur=node(x,levelY+depth*150,n.title,{shape:n.yes||n.no?'diamond':'rect',color:palette[depth%palette.length],desc:n.description,filled:!(n.yes||n.no),w:n.yes||n.no?190:150});if(n.yes){const child=walk(n.yes,x-span/2,depth+1,span/1.8);edge(cur.x,cur.y+cur.h/2,child.x,child.y-child.h/2,'Yes','#0E8F7A')}if(n.no){const child=walk(n.no,x+span/2,depth+1,span/1.8);edge(cur.x,cur.y+cur.h/2,child.x,child.y-child.h/2,'No','#B64872')}return cur}walk(d.root,0,0,620)}
function renderMatrix(d){title(d.title);const cols=d.columns||[],rows=d.rows||[],cellW=170,rowH=62,left=-((cols.length+1)*cellW)/2,top=-170,all=[['',...cols],...rows.map(r=>[r.label,...r.values])];all.forEach((row,ri)=>row.forEach((txt,ci)=>{const x=left+ci*cellW,y=top+ri*rowH;scene.append(svg('rect',{x,y,width:cellW,height:rowH,fill:ri===0?'#E9EDFF':ci===0?'#F5F7FB':'#fff',stroke:'#CBD5E1'}));const ls=wrap(txt,10);ls.forEach((ln,j)=>scene.append(svg('text',{x:x+cellW/2,y:y+rowH/2+(j-(ls.length-1)/2)*18+5,'text-anchor':'middle',fill:'#243046','font-size':13,'font-family':'system-ui,sans-serif','font-weight':ri===0||ci===0?'700':'500'},ln)));include(x,y,cellW,rowH)}))}
function renderFormula(d){title(d.title);(d.formulas||[]).forEach((f,i)=>{const y=-120+i*170;node(0,y,f.name,{w:260,color:palette[i%palette.length],filled:true,desc:f.note});node(0,y+72,f.formula,{w:430,color:palette[i%palette.length],desc:f.note});if(f.note){scene.append(svg('text',{x:0,y:y+128,'text-anchor':'middle',fill:'#64748B','font-size':13,'font-family':'system-ui,sans-serif'},f.note));include(-250,y+110,500,35)}})}
function renderHierarchy(d){title(d.title);const root=d.root;if(!root)return;const r=node(0,-120,root.title,{w:220,filled:true}),ch=root.children||[],gap=230,start=-(ch.length-1)*gap/2;ch.forEach((c,i)=>{const n=node(start+i*gap,90,c.title,{color:palette[(i+1)%palette.length],desc:c.description});edge(r.x,r.y+r.h/2,n.x,n.y-n.h/2,'',palette[(i+1)%palette.length])})}
function renderExam(d){title(d.title);const sec=d.sections||[],cols=2,w=330,h=170,gapX=370,gapY=205;sec.forEach((s,i)=>{const c=i%cols,r=Math.floor(i/cols),x=(c-.5)*gapX,y=-120+r*gapY;scene.append(svg('rect',{x:x-w/2,y:y-h/2,width:w,height:h,rx:18,fill:'#fff',stroke:palette[i%palette.length],'stroke-width':2.5}));scene.append(svg('rect',{x:x-w/2,y:y-h/2,width:w,height:42,rx:18,fill:palette[i%palette.length]}));scene.append(svg('text',{x,y:y-h/2+27,'text-anchor':'middle',fill:'#fff','font-size':15,'font-family':'system-ui,sans-serif','font-weight':'700'},s.title));(s.items||[]).forEach((it,j)=>scene.append(svg('text',{x:x-w/2+22,y:y-h/2+68+j*25,fill:'#334155','font-size':13,'font-family':'system-ui,sans-serif'},'• '+it)));include(x-w/2-10,y-h/2-10,w+20,h+20)})}
function renderProductProcess(d){title(d.title);const p=d.products||[],m=d.processes||[],cw=165,rh=74,left=-((p.length+1)*cw)/2,top=-160;[['',...p],...m.map((x,i)=>[x,...p.map((_,j)=>i===j?'✓':'')])].forEach((row,ri)=>row.forEach((txt,ci)=>{const x=left+ci*cw,y=top+ri*rh,isMatch=ri>0&&ci>0&&ri-1===ci-1;scene.append(svg('rect',{x,y,width:cw,height:rh,fill:isMatch?'#E8F7F1':ri===0?'#E9EDFF':ci===0?'#F5F7FB':'#fff',stroke:'#CBD5E1'}));const ls=wrap(txt,9);ls.forEach((ln,j)=>scene.append(svg('text',{x:x+cw/2,y:y+rh/2+(j-(ls.length-1)/2)*18+5,'text-anchor':'middle',fill:isMatch?'#0E8F7A':'#243046','font-size':13,'font-family':'system-ui,sans-serif','font-weight':isMatch||ri===0||ci===0?'700':'500'},ln)));include(x,y,cw,rh)}));if(d.note)detail.textContent=d.note}
function renderPQ(d){title(d.title);const ox=-330,oy=190,w=660,h=390;scene.append(svg('line',{x1:ox,y1:oy,x2:ox+w,y2:oy,stroke:'#475569','stroke-width':2}));scene.append(svg('line',{x1:ox,y1:oy,x2:ox,y2:oy-h,stroke:'#475569','stroke-width':2}));scene.append(svg('text',{x:ox+w/2,y:oy+34,'text-anchor':'middle',fill:'#475569','font-size':13},'產品種類 P →'));scene.append(svg('text',{x:ox-42,y:oy-h/2,transform:`rotate(-90 ${ox-42} ${oy-h/2})`,'text-anchor':'middle',fill:'#475569','font-size':13},'產量 Q →'));(d.classes||[]).forEach((c,i)=>{const x=ox+(c.productVariety/10)*w,y=oy-(c.quantity/10)*h;const n=node(x,y,c.name,{w:120,h:52,color:palette[i%palette.length],filled:true,desc:`${c.description||''} ${c.layout||''}`});scene.append(svg('text',{x:n.x,y:n.y+n.h/2+25,'text-anchor':'middle',fill:'#64748B','font-size':12},c.layout||''))});include(ox-60,oy-h-30,w+100,h+90)}
function renderMistakes(d){title(d.title);const pairs=d.pairs||[],cw=330,rh=112,left=-360,top=-170;scene.append(svg('text',{x:left+cw/2,y:top-22,'text-anchor':'middle',fill:'#B64872','font-size':16,'font-weight':'700'},'容易搞錯'));scene.append(svg('text',{x:left+cw+60+cw/2,y:top-22,'text-anchor':'middle',fill:'#0E8F7A','font-size':16,'font-weight':'700'},'正確觀念'));pairs.forEach((p,i)=>{const y=top+i*(rh+18);for(const [x,txt,color] of [[left,p.wrong,'#FFF1F3'],[left+cw+60,p.right,'#ECFDF5']]){scene.append(svg('rect',{x,y,width:cw,height:rh,rx:14,fill:color,stroke:'#CBD5E1'}));wrap(txt,18).forEach((ln,j)=>scene.append(svg('text',{x:x+cw/2,y:y+36+j*20,'text-anchor':'middle',fill:'#243046','font-size':13,'font-weight':'600'},ln)))}scene.append(svg('text',{x:0,y:y+rh-14,'text-anchor':'middle',fill:'#64748B','font-size':11},p.tip||''));include(left-10,y-10,cw*2+80,rh+20)})}
function renderDependency(d){title(d.title);const nodes=d.nodes||[],levels=new Map();nodes.forEach(n=>{const lv=Number.isFinite(n.level)?n.level:0;if(!levels.has(lv))levels.set(lv,[]);levels.get(lv).push(n)});if(!nodes.some(n=>Number.isFinite(n.level))){nodes.forEach((n,i)=>{const lv=i;levels.set(lv,[n])})}const map=new Map(),sorted=[...levels.keys()].sort((a,b)=>a-b);sorted.forEach((lv,li)=>{const arr=levels.get(lv),gap=230,start=-(arr.length-1)*gap/2;arr.forEach((n,i)=>map.set(n.id,node(start+i*gap,-180+li*150,n.title,{color:palette[li%palette.length],desc:n.description,filled:li===0}))) });(d.relations||[]).forEach((r,i)=>{const a=map.get(r.from),b=map.get(r.to);if(a&&b)edge(a.x,a.y+a.h/2,b.x,b.y-b.h/2,r.label||'',palette[(i+1)%palette.length])})}
function render(data){try{current=data;resetScene();status.textContent='';detail.textContent='點選節點查看說明。';switch(data.type){case'concept_map':renderConcept(data);break;case'cause_effect':case'process_flow':renderFlowLike(data);break;case'decision_tree':renderDecision(data);break;case'comparison_matrix':renderMatrix(data);break;case'formula_map':renderFormula(data);break;case'hierarchy_map':renderHierarchy(data);break;case'exam_overview':renderExam(data);break;case'product_process_matrix':renderProductProcess(data);break;case'pq_analysis':renderPQ(data);break;case'mistake_contrast':renderMistakes(data);break;case'prerequisite_map':case'dependency_map':renderDependency(data);break;default:throw Error('尚未支援此 type：'+data.type)}fit();status.textContent='已產生：'+data.title}catch(e){status.textContent='產生失敗：'+e.message}}
function transform(){scene.setAttribute('transform',`translate(${tx},${ty}) scale(${zoom})`)}
function fit(){const r=canvas.getBoundingClientRect();if(!isFinite(bounds.x))return;const w=bounds.right-bounds.x,h=bounds.bottom-bounds.y;zoom=Math.max(.15,Math.min(1.25,(r.width-80)/w,(r.height-190)/h));tx=r.width/2-(bounds.x+bounds.right)/2*zoom;ty=r.height/2-(bounds.y+bounds.bottom)/2*zoom;transform()}
function loadTemplate(t){input.value=JSON.stringify(t.data,null,2);render(t.data);document.querySelectorAll('.template-card').forEach(b=>b.classList.toggle('recommended',b.dataset.id===t.id))}
function initTemplates(){window.KSS_TEMPLATES.forEach(t=>{const b=document.createElement('button');b.className='template-card';b.dataset.id=t.id;b.innerHTML=`<strong>${t.label}</strong><small>${t.desc}</small>`;b.onclick=()=>loadTemplate(t);$('templateList').appendChild(b)});loadTemplate(window.KSS_TEMPLATES[0])}
function save(text,type,name){const u=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function exportSVG(asPng=false){if(!isFinite(bounds.x))return;const x=bounds.x-30,y=bounds.y-30,w=bounds.right-bounds.x+60,h=bounds.bottom-bounds.y+60,copy=canvas.cloneNode(true);copy.removeAttribute('id');copy.setAttribute('viewBox',`${x} ${y} ${w} ${h}`);copy.setAttribute('width',w);copy.setAttribute('height',h);copy.querySelector('g').removeAttribute('transform');copy.insertBefore(svg('rect',{x,y,width:w,height:h,fill:'#f8fafc'}),copy.firstChild);const src=new XMLSerializer().serializeToString(copy);if(!asPng){save(src,'image/svg+xml','knowledge-structure.svg');return}const u=URL.createObjectURL(new Blob([src],{type:'image/svg+xml'})),img=new Image();img.onload=()=>{const c=document.createElement('canvas');c.width=w*2;c.height=h*2;c.getContext('2d').drawImage(img,0,0,c.width,c.height);c.toBlob(b=>{const u2=URL.createObjectURL(b),a=document.createElement('a');a.href=u2;a.download='knowledge-structure.png';a.click();setTimeout(()=>URL.revokeObjectURL(u2),1000)},'image/png');URL.revokeObjectURL(u)};img.src=u}
function recommend(text){const s=text.toLowerCase();const rules=[
  ['decision_tree',['是否','要不要','決策','yes','no','選擇','判斷']],
  ['comparison_matrix',['比較','差異','優缺點','vs','對照','種類']],
  ['formula_map',['公式','計算','效率','利用率','變數']],
  ['cause_effect',['因果','導致','造成','影響','因此','原因']],
  ['process_flow',['流程','步驟','sop','程序','順序']],
  ['product_process_matrix',['產品－製程','產品-製程','product process','對角線']],
  ['pq_analysis',['p-q','pq','產品產量','產量分析']],
  ['mistake_contrast',['易錯','搞混','常錯','陷阱']],
  ['prerequisite_map',['前置','先學','基礎知識']],
  ['dependency_map',['依賴','關聯','串聯','前後關係']],
  ['hierarchy_map',['分類','層級','包含','類型']],
  ['exam_overview',['考前','總整理','總覽','複習','一頁']],
  ['concept_map',['概念','關係','知識','理解']]
];
  const scored=rules.map(([id,keys])=>({id,score:keys.reduce((n,k)=>n+(s.includes(k)?1:0),0)})).sort((a,b)=>b.score-a.score);return scored.filter(x=>x.score>0).slice(0,3).map(x=>window.KSS_TEMPLATES.find(t=>t.id===x.id)).filter(Boolean)
}
$('renderBtn').onclick=()=>{try{render(JSON.parse(input.value))}catch(e){status.textContent='JSON 錯誤：'+e.message}};
$('sampleBtn').onclick=()=>loadTemplate(window.KSS_TEMPLATES.find(t=>t.id===(current?.type||'concept_map'))||window.KSS_TEMPLATES[0]);
$('fitBtn').onclick=fit;$('resetBtn').onclick=fit;$('zoomInBtn').onclick=()=>{zoom=Math.min(4,zoom*1.2);transform()};$('zoomOutBtn').onclick=()=>{zoom=Math.max(.08,zoom/1.2);transform()};
$('saveJsonBtn').onclick=()=>save(input.value,'application/json','knowledge-structure.json');$('exportSvgBtn').onclick=()=>exportSVG(false);$('exportPngBtn').onclick=()=>exportSVG(true);
$('copyPromptBtn').onclick=async()=>{const prompt=`請把我要學習的內容轉成 Knowledge Structure Studio 的 JSON。可用 type：${window.KSS_TEMPLATES.map(t=>t.id).join('、')}。只輸出合法 JSON，不要 Markdown。\n\n目前範例：\n${input.value}`;await navigator.clipboard.writeText(prompt);status.textContent='已複製 AI 提示詞。'};
$('recommendBtn').onclick=()=>{const text=$('courseInput').value.trim(),box=$('recommendation');if(!text){box.hidden=false;box.innerHTML='<strong>請先貼入課程內容。</strong>';return}const picks=recommend(text);box.hidden=false;if(!picks.length){box.innerHTML='<strong>建議：概念圖</strong>目前沒有明顯關鍵詞，先用概念圖整理主題與關係。';return}box.innerHTML=`<strong>推薦圖形</strong><div>依你貼入的文字關鍵詞排序：</div><div class="chips">${picks.map(t=>`<span class="chip"><button data-template="${t.id}">${t.label}</button></span>`).join('')}</div>`;box.querySelectorAll('[data-template]').forEach(b=>b.onclick=()=>{const t=window.KSS_TEMPLATES.find(x=>x.id===b.dataset.template);if(t)loadTemplate(t)})};
$('clearCourseBtn').onclick=()=>{$('courseInput').value='';$('recommendation').hidden=true};
canvas.onpointerdown=e=>{if(e.target.closest('g[style*="cursor:pointer"]'))return;drag={x:e.clientX,y:e.clientY,tx,ty};canvas.setPointerCapture(e.pointerId)};canvas.onpointermove=e=>{if(drag){tx=drag.tx+e.clientX-drag.x;ty=drag.ty+e.clientY-drag.y;transform()}};canvas.onpointerup=canvas.onpointercancel=()=>drag=null;canvas.addEventListener('wheel',e=>{e.preventDefault();const r=canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top,n=Math.max(.08,Math.min(4,zoom*Math.exp(-e.deltaY*.001)));tx=x-(x-tx)*n/zoom;ty=y-(y-ty)*n/zoom;zoom=n;transform()},{passive:false});window.addEventListener('resize',fit);
initTemplates();
})();
